const words = 
[
    "Tap me", 
    "Don't at me", 
    "Laiwip", 
    "YOOOOOOOOOOOOOOO", 
    "Is this text really random", 
    "No",
    "The next color might be blue", 
    "That sort of hurts", 
    "Seen", 
    "I got really bored one day and started writing these out",
    "Need Blog ideas", 
    "Why u wanna blog",
    "yo could you guys pm me random words ?", 
    "Z",
    "The Second Law of Thermodynamics states that the state of entropy of the entire universe, as an isolated system, will always increase over time",
    "This will repeat too", 
    "Cat 🐱", 
    "Dog 🐶", 
    "The great part of randomness is.. Oh look the number changed", 
    "I sometimes flex infront of the mirror", 
    "There might be a story in all of this",
    "its 10:14 pm when I am writing this", 
    "Can WE be friends?", 
    "might be", 
    "Ok", 
    "a little bit", 
    "Radical", 
    "Cool", 
    "Neato", 
    "I am trying so hard to not use brand names",
    "Some of these might be lyrics", 
    "You stress me out", 
    "Let me tell you the story of the 🐢 and the 🐍", 
    "The 🐢 is the 🐍", 
    "This is really cool", 
    "I am going to give this five starts at the store",
    "🐍🐍🐍🐍🐍🐍🐍🐍🐍🐍🐍🐍🐍🐍", 
    "🐢🐢🐢🐢🐢🐢🐢🐢🐢🐢🐢🐢", 
    "Your text could be here", 
    "some active users", 
    "Translate this", 
    "je ne sais pas", 
    "এই অ্যাপ্লিকেশন সত্যিই শীতল", 
    "I really hope unicode is supported",
    "我一直想学习普通话", 
    "حسنا", 
    "מיטאַרבעט", 
    "මාළු සැරසිලි", 
    "Estoy aburrido", 
    "เปิดตา", 
    "яйця", 
    "send me more random words and phrases",
];


export default words;